### ISSUE TITLE
Question: I added default values to arguments but they're not appearing when I use the workflow, is this a bug or intentional?

### ISSUE THREAD

**Issue by zoominGiladSher** [warpdotdev/workflows#65]
I created the following workflow locally and added arguments as specified in the `.md` file in the repo, however, when trying to use the workflow it shows up with the arguments names instead of the default values. Is this intentional or a bug? If intentional, what's the purpose of having default values for arguments? Maybe I'm just using it incorrectly... Anyhow, would be glad to get some help :)

```yaml
name: Upload file to local backend
command: "java -jar {{suitebundleLocation}} upload -u {{serverURL}} -p {{uploadPassword}} -b {{zipFileLocation}} -n {{bundleName}}"
tags:
  - backend
  - BE
  - upload
  - bundle
arguments:
  - name: suitebundleLocation
    description: The full path to the `suitebundle.jar` file. Default = ~/Downloads/suitebundle.jar
    default_value: ~/Downloads/suitebundle.jar
  - name: serverURL
    description: The backend URL to which the file should be uploaded. Default = https://localhost:3443
    default_value: https://localhost:3443
  - name: uploadPassword
    description: The upload password from the backend config
    default_value: '12345'
  - name: zipFileLocation
    description: The full path to the bundle with the `.zip` suffix. E.G. ~/Downloads/test-bundle.zip
  - name: bundleName
    description: The name that the bundle will have on the backend server
description: "Uploads a bundle to the backend server"
```

So far really enjoying Warp!

Using MacBook Pro (13-inch, M1, 2020)
MacOS Monterey 12.3.1 (21E258)
