### ISSUE TITLE
Don't support multi workflows defined in a single yaml file ?

### ISSUE THREAD

**Issue by xinxinh2020** [warpdotdev/workflows#91]
I has a local workflow file like:
```yaml
---
name: Show Open vswitch bridges
command: |-
    ovs-vsctl show
tags:
  - ovs
shells: []

---
name: Add a Open vswitch bridge
command: |-
    ovs-vsctl add-br {{bridge_name}}
tags:
  - ovs
description: Add a bridge
arguments:
  - name: bridge_name
    description: The name of the bridge that should be added
    default_value: mybridge
shells: []
```

I suppose that it will have two custom workflows recognized by warp and it doesn't work.
Can warp recognize multi workflows defined in a single yaml file now?
